// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plnwbbkzodhxcigaopxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbndiYmt6b2RoeGNpZ2FvcHhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MDM2NTYsImV4cCI6MjA2Mzk3OTY1Nn0.t-iJkUYoFc1T__pdCVcol3f1YGOdJ53XGZGCXQbQInY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);